spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: http://localhost:8081
              predicates:
                - Path=/patients/**
              filters:
                - AddRequestHeader=X-Gateway-Secret,${GATEWAY_SECRET}
            - id: notes-service
              uri: http://localhost:8083
              predicates:
                - Path=/notes/**
              filters:
                - AddRequestHeader=X-Gateway-Secret,${GATEWAY_SECRET}

server:
  port: 8080