spring.application.name=assessment-service
server.port=8084

patient-service.base-url=${PATIENT_SERVICE_URL:http://localhost:8081}
notes-service.base-url=${NOTES_SERVICE_URL:http://localhost:8083}

jwt.public-key-path=${JWT_PUBLIC_KEY_PATH:classpath:keys/public_key.pem}
jwt.issuer=medilabo-gateway

management.endpoints.web.exposure.include=health